package EjerciciosDeProgramación;

public class Ejercicio8 {
    public static void main(String[] args) {
        System.out.println("  ____||____");
        System.out.println("////////////|");
        System.out.println("|    _    | |");
        System.out.println("|[] | | []|_|");
        System.out.println("|   |─|   | /");
        System.out.println("└─────────┘/ ");
        System.out.println("   |   |");
        System.out.println("  |#   #|");
        System.out.println(" |#  ~  #|");
        System.out.println("|_#_____#_|");
    }
}